name: build executables

on:
  push:
    tags:
      - 'v*'
  #   branches: [ "release" ]
  # pull_request:
  #   branches: [ "release" ]

env:
  VERSION: ${{ github.ref_name }}

jobs:
  pyinstaller-builds:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ${{ matrix.os }}-latest
    permissions:
      contents: write
    strategy:
      matrix:
        # os: [ubuntu]
        include:
          # - os: ubuntu
          #   file_extension: ""
          #   options: --onefile
          # - os: macos
          #   file_extension: ".app"
          #   options: --windowed
          - os: windows
            file_extension: ".exe"
            options: --windowed
    steps:
      - name: Create Standalone Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: "3.11"
          spec: "axoden/gui/gui_projections_quantification.py"
          requirements: "requirements.txt"
          upload_exe_with_name: "Axoden_${{ env.VERSION }}.${{ matrix.file_extension }}"
          options: ${{ matrix.options }} --name "Axoden_${{ env.VERSION }}_${{ matrix.os }}" --hidden-import="PIL._tkinter_finder"

      - name: Echo
        run: ls -laG dist

      - name: Zip executable
        run: cd dist && zip -r Axoden_${{ env.VERSION }}_${{ matrix.os }}.zip Axoden_${{ env.VERSION }}_${{ matrix.os}}${{ matrix.file_extension }}

      - name: Echo
        run: ls -laG dist
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/Axoden_${{ env.VERSION }}_${{ matrix.os }}.zip
