name: build executables

on: workflow_dispatch
  # push:
  #   tags:
  #     - 'v*'

env:
  VERSION: ${{ github.ref_name }}

jobs:
  pyinstaller-builds:
    # if: startsWith(github.ref, 'refs/tags/')
    runs-on: ${{ matrix.os }}-latest
    permissions:
      contents: write
    strategy:
      matrix:
        # os: [ubuntu]
        include:
          # - os: ubuntu
          #   file_extension: ""
          #   options: --onefile
          # - os: macos
          #   file_extension: ".app"
          #   options: --windowed
          - os: windows
            file_extension: ".exe"
            options: --windowed
    steps:
      # - name: Create Standalone Executable
      #   uses: sayyid5416/pyinstaller@v1
      #   with:
      #     python_ver: "3.11"
      #     spec: "axoden/gui/gui_projections_quantification.py"
      #     requirements: "requirements.txt"
      #     # upload_exe_with_name: "Axoden_${{ env.VERSION }}.${{ matrix.file_extension }}"
      #     options: ${{ matrix.options }} --distpath dist --name "Axoden_${{ env.VERSION }}" --hidden-import="PIL._tkinter_finder"

      # - name: Echo
      #   run: ls -laG dist
      - name: Echo ubuntu
        if: ${{ matrix.os == 'ubuntu' }}
        run: echo "ubuntu"
      - name: Echo windows
        if: ${{ matrix.os == 'windows' }}
        run: echo "Windows"
      - name: Echo ubuntu mac
        if: ${{ matrix.os == 'ubuntu' || matrix.os == 'macos' }}
        run: echo "ubuntu or mac"

      - name: Echo if condition
        run: echo ${{ matrix.os == 'ubuntu' }}
      - name: Echo if condition 2
        run: echo ${{ matrix.os == 'ubuntu' || matrix.os == 'macos' }}

      # - name: Zip executable
      #   if: ${{ matrix.os == 'ubuntu' || matrix.os == 'macos' }}
      #   run: cd dist && zip -r Axoden_${{ env.VERSION }}_${{ matrix.os }}.zip Axoden_${{ env.VERSION }}${{ matrix.file_extension }}

      # - name: Echo
      #   run: ls -laG dist

      # - name: Release
      #   uses: softprops/action-gh-release@v2
      #   if: startsWith(github.ref, 'refs/tags/')
      #   with:
      #     files: |
      #       dist/Axoden_${{ env.VERSION }}_${{ matrix.os }}.zipo
