name: build executables

on:
  push:
    tags:
      - 'v*'

env:
  VERSION: ${{ github.ref_name }}

jobs:
  pyinstaller-builds:
    # if: startsWith(github.ref, 'refs/tags/')
    runs-on: ${{ matrix.os }}-latest
    permissions:
      contents: write
    strategy:
      matrix:
        # os: [ubuntu]
        include:
          # - os: ubuntu
          #   file_extension: ""
          #   options: --onefile
          #   dir: "dist"
          # - os: macos
          #   file_extension: ".app"
          #   options: --windowed
          #   dir: "dist"
          - os: windows
            file_extension: ".exe"
            options: --windowed
            dir: "build/Axoden_${{ github.ref_name }}"
    steps:
      - name: Create Standalone Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: "3.11"
          spec: "axoden/gui/gui_projections_quantification.py"
          requirements: "requirements.txt"
          # upload_exe_with_name: "Axoden_${{ env.VERSION }}.${{ matrix.file_extension }}"
          options: ${{ matrix.options }} --name "Axoden_${{ env.VERSION }}" --hidden-import="PIL._tkinter_finder"

      - name: Echo
        run: ls ${{ matrix.dir }}

      - name: Zip executable
        if: ${{ matrix.os == 'ubuntu' || matrix.os == 'macos' }}
        run: cd ${{ matrix.dir }} && zip Axoden_${{ env.VERSION }}_${{ matrix.os }}.zip Axoden_${{ env.VERSION }}${{ matrix.file_extension }}

      - name: Zip executable
        if: ${{ matrix.os == 'windows' }}
        run: cd ${{ matrix.dir }} && powershell Compress-Archive Axoden_${{ env.VERSION }}${{ matrix.file_extension }} Axoden_${{ env.VERSION }}_${{ matrix.os }}.zip

      - name: Echo
        run: ls ${{ matrix.dir }}

      # - name: Rename executable
      #   if: ${{ matrix.os == 'windows' }}
      #   run: mv ${{ matrix.dir }}/Axoden_${{ env.VERSION }}.zip ${{ matrix.dir }}/Axoden_${{ env.VERSION }}_${{ matrix.os }}.zip

      - name: Echo
        run: ls ${{ matrix.dir }}

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${{ matrix.dir }}/Axoden_${{ env.VERSION }}_${{ matrix.os }}.zip
