name: build executables

on: workflow_dispatch
  # push:
  #   branches: [ "release" ]
  # pull_request:
  #   branches: [ "release" ]

jobs:
  pyinstaller-builds:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [ubuntu]
        # os: [ubuntu, macos, windows]
    steps:
      - name: Create Standalone Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: "3.11"
          spec: "axoden/gui/gui_projections_quantification.py"
          requirements: "requirements.txt"
          upload_exe_with_name: "Axoden-${{ matrix.os }}"
          options: --onefile --name "Axoden" --hidden-import="PIL._tkinter_finder"
