on: workflow_dispatch
  # push:
  #   branches: [ "release" ]
  # pull_request:
  #   branches: [ "release" ]

jobs:
  pyinstaller-builds:
    runs-on: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Create Standalone Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.11'
          requirements: 'requirements.txt'
          upload_exe_with_name: "Axoden executable"
          options: --onefile --name "Axoden"
