name: build executables

on: workflow_dispatch
  # push:
  #   branches: [ "release" ]
  # pull_request:
  #   branches: [ "release" ]

env:
  VERSION: "v0.2.0"

jobs:
  pyinstaller-builds:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        # os: [ubuntu]
        include:
          - os: ubuntu
            file_extension: pgk
          # - os: macos
          #   file_extension: "Axoden.app"
          # - os: windows
          #   file_extension: "Axoden.exe"
        # os: [ubuntu, macos, windows]
    steps:
      - name: Create Standalone Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: "3.11"
          spec: "axoden/gui/gui_projections_quantification.py"
          requirements: "requirements.txt"
          upload_exe_with_name: "Axoden_${{ env.VERSION }}.${{ matrix.file_extension }}" # it has .pkg ending...
          options: --onefile --name "Axoden_${{ env.VERSION }}.${{ matrix.file_extension }}" --hidden-import="PIL._tkinter_finder"
      - name: Echo
        run: ls -laG dist
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          if: startsWith(github.ref, 'refs/tags/')
          files: |
            dist/Axoden_${{ env.VERSION }}.${{ matrix.file_extension }}
