name: Build Documentation

on:
  push:
    branches:
      - main
#   release:
#     types: [created]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install sphinx
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install sphinx
      - name: Build docs with sphinx
        run: cd docs && make html
      - name: Publish github pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html

