name: publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install flit
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install flit
      - name: Publish to PyPi
        env:
          FLIT_USERNAME: __token__
          FLIT_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: flit publish